services:
  speakcheck_app:
    build: .
    container_name: speakcheck_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: always
